# Join Statements

## Introduction

In this section, you will learn about several types of join statements.  Joins are the primary mechanism for combining data from multiple tables. In order to do this, you define the common attribute(s) between tables in order for them to be combined.

## Objectives  

You will be able to:  
 
* Compare and contrast the various types of joins
* Discuss the syntax and structure of join statements
* Discuss the role of foreign and primary keys in them

## CRM Schema

In almost all industry cases, rather than just working with a single table you will generally need data from multiple tables. Doing this requires the use of **joins** using shared columns from the two tables. For example, here's a diagram of a mock customer relationship management database.
<img src='images/Database-Schema.png' width=550>

## Connecting to the Database

As usual, you'll start by connecting to the database.

In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect('data.sqlite', detect_types=sqlite3.PARSE_COLNAMES)
cur = conn.cursor()

## Displaying product details along with order details
Let's say you need to generate some report that includes details about products from orders. To do that, we would need to take data from multiple tables in a single statement.

In [3]:
cur.execute("""select * from orderdetails
                        join products
                        on orderdetails.productCode = products.productCode
                        limit 10;
                       """)
df = pd.DataFrame(cur.fetchall()) #Take results and create dataframe
df.columns = [i[0] for i in cur.description]
df.head()

,orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
0,10100,S18_1749,30,136.00,3,S18_1749,1917 Grand Touring Sedan,Vintage Cars,1:18,Welly Diecast Productions,This 1:18 scale replica of the 1917 Grand Tour...,2724,86.70,170.00
1,10100,S18_2248,50,55.09,2,S18_2248,1911 Ford Town Car,Vintage Cars,1:18,Motor City Art Classics,"Features opening hood, opening doors, opening ...",540,33.30,60.54
2,10100,S18_4409,22,75.46,4,S18_4409,1932 Alfa Romeo 8C2300 Spider Sport,Vintage Cars,1:18,Exoto Designs,This 1:18 scale precision die cast replica fea...,6553,43.26,92.03
3,10100,S24_3969,49,35.29,1,S24_3969,1936 Mercedes Benz 500k Roadster,Vintage Cars,1:24,Red Start Diecast,This model features grille-mounted chrome horn...,2081,21.75,41.03
4,10101,S18_2325,25,108.06,4,S18_2325,1932 Model A Ford J-Coupe,Vintage Cars,1:18,Autoart Studio Design,This model features grille-mounted chrome horn...,9354,58.48,127.13

## Compared to the individual tables:

### orderdetails

In [4]:
cur.execute("""select * from orderdetails limit 10;""")
df = pd.DataFrame(cur.fetchall()) #Take results and create dataframe
df.columns = [i[0] for i in cur.description]
df.head()

  orderNumber productCode quantityOrdered priceEach orderLineNumber
0       10100    S18_1749              30    136.00               3
1       10100    S18_2248              50     55.09               2
2       10100    S18_4409              22     75.46               4
3       10100    S24_3969              49     35.29               1
4       10101    S18_2325              25    108.06               4

### products

In [5]:
cur.execute("""select * from products limit 10;""")
df = pd.DataFrame(cur.fetchall()) #Take results and create dataframe
df.columns = [i[0] for i in cur.description]
df.head()

,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
0,S10_1678,1969 Harley Davidson Ultimate Chopper,Motorcycles,1:10,Min Lin Diecast,"This replica features working kickstand, front...",7933,48.81,95.70
1,S10_1949,1952 Alpine Renault 1300,Classic Cars,1:10,Classic Metal Creations,Turnable front wheels; steering function; deta...,7305,98.58,214.30
2,S10_2016,1996 Moto Guzzi 1100i,Motorcycles,1:10,Highway 66 Mini Classics,"Official Moto Guzzi logos and insignias, saddl...",6625,68.99,118.94
3,S10_4698,2003 Harley-Davidson Eagle Drag Bike,Motorcycles,1:10,Red Start Diecast,"Model features, official Harley Davidson logos...",5582,91.02,193.66
4,S10_4757,1972 Alfa Romeo GTA,Classic Cars,1:10,Motor City Art Classics,Features include: Turnable front wheels; steer...,3252,85.68,136.00

## the using clause
A more concise way to join the tables if the column name is identical is the using clause. Rather then saying on `tableA.column = tableB.column` we can simply say `using(column)`. Again, this only works if the column is identically named for both tables.

In [6]:
cur.execute("""select * from orderdetails
                        join products
                        using(productCode)
                        limit 10;
                       """)
df = pd.DataFrame(cur.fetchall()) #Take results and create dataframe
df.columns = [i[0] for i in cur.description]
df.head()

,orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
0,10100,S18_1749,30,136.00,3,1917 Grand Touring Sedan,Vintage Cars,1:18,Welly Diecast Productions,This 1:18 scale replica of the 1917 Grand Tour...,2724,86.70,170.00
1,10100,S18_2248,50,55.09,2,1911 Ford Town Car,Vintage Cars,1:18,Motor City Art Classics,"Features opening hood, opening doors, opening ...",540,33.30,60.54
2,10100,S18_4409,22,75.46,4,1932 Alfa Romeo 8C2300 Spider Sport,Vintage Cars,1:18,Exoto Designs,This 1:18 scale precision die cast replica fea...,6553,43.26,92.03
3,10100,S24_3969,49,35.29,1,1936 Mercedes Benz 500k Roadster,Vintage Cars,1:24,Red Start Diecast,This model features grille-mounted chrome horn...,2081,21.75,41.03
4,10101,S18_2325,25,108.06,4,1932 Model A Ford J-Coupe,Vintage Cars,1:18,Autoart Studio Design,This model features grille-mounted chrome horn...,9354,58.48,127.13

## Aliasing
Alternatively, you can also alias tables by giving them an alternative shorthand name directly after them. Here we use the aliases 'o' and 'p' for orderdetails and products respectively.

In [7]:
cur.execute("""select * from orderdetails o
                        join products p
                        on o.productCode = p.productCode
                        limit 10;
                       """)
df = pd.DataFrame(cur.fetchall()) #Take results and create dataframe
df.columns = [i[0] for i in cur.description]
df.head()

,orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
0,10100,S18_1749,30,136.00,3,S18_1749,1917 Grand Touring Sedan,Vintage Cars,1:18,Welly Diecast Productions,This 1:18 scale replica of the 1917 Grand Tour...,2724,86.70,170.00
1,10100,S18_2248,50,55.09,2,S18_2248,1911 Ford Town Car,Vintage Cars,1:18,Motor City Art Classics,"Features opening hood, opening doors, opening ...",540,33.30,60.54
2,10100,S18_4409,22,75.46,4,S18_4409,1932 Alfa Romeo 8C2300 Spider Sport,Vintage Cars,1:18,Exoto Designs,This 1:18 scale precision die cast replica fea...,6553,43.26,92.03
3,10100,S24_3969,49,35.29,1,S24_3969,1936 Mercedes Benz 500k Roadster,Vintage Cars,1:24,Red Start Diecast,This model features grille-mounted chrome horn...,2081,21.75,41.03
4,10101,S18_2325,25,108.06,4,S18_2325,1932 Model A Ford J-Coupe,Vintage Cars,1:18,Autoart Studio Design,This model features grille-mounted chrome horn...,9354,58.48,127.13

## Left Joins

By default, a join is an inner join, or the intersection between two tables. In other words, the join between orders and products is only for productCodes that are in both the orderdetails and products tables. If a product had yet to be ordered (and wasn't in the orderdetails table) then it would also not be in the result of the join.

There are many other types of joins, displayed below. Of these, sqlite does not support outer joins, but it is good to be aware of as more powerful versions of sql such as PostgreSQL support these additional functions.

<img src='images/venn.png' width="700">

For example, the statement  
  
`select * from products left join orderdetails; `  

would return all products, even those that hadn't been ordered. 
You can imagine that all products in inventory should have a description in the product table, but perhaps not every product is represented in the orderdetails table.

In [3]:
cur.execute("""select * from products
                        left join orderdetails
                        using(productCode);
                       """)
df = pd.DataFrame(cur.fetchall()) #Take results and create dataframe
df.columns = [i[0] for i in cur.description]
print(len(df))
print(len(df[df.orderNumber.isnull()]))
df[df.orderNumber.isnull()].head()

2997
1

,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP,orderNumber,quantityOrdered,priceEach,orderLineNumber
1122,S18_3233,1985 Toyota Supra,Classic Cars,1:18,Highway 66 Mini Classics,"This model features soft rubber tires, working...",7733,57.01,107.57,None,None,None,None

As you can see, its rare, but there is one product that has yet to be ordered

## Primary Versus Foreign Keys

Another important consideration when performing joins is to think more about the key or column you are joining on. As you'll see in upcoming lessons, this can lead to interesting behavior if the join value is not unique in one or both of the tables. In all of the above examples, you joined two tables using the **primary key**. The primary key(s) of a table are those column(s) which uniquely identify a row. You'll also see this designated in our schema diagram with the asterisk (*).
<img src='images/Database-Schema.png' width=550>

You can also join tables using **foreign keys** which are not the primary key for that particular table, but rather another table. For example, employeeNumber is the primary key for the employees table and corresponds to the salesRepEmployeeNumber of the customers table. In the customers table, salesRepEmployeeNumber is only a foreign key, and is unlikely to be a unique identifier, as it is likely that an employee serves multiple customers. As such, in the resulting view, employeeNumber would no longer be a unique field.

In [5]:
cur.execute("""select * from customers c
                        join employees e
                        on c.salesRepEmployeeNumber = e.employeeNumber
                        order by employeeNumber;
                       """)
df = pd.DataFrame(cur.fetchall()) #Take results and create dataframe
df.columns = [i[0] for i in cur.description]
df.head(50)

,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,...,salesRepEmployeeNumber,creditLimit,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,124,Mini Gifts Distributors Ltd.,Nelson,Susan,4155551450,5677 Strong St.,,San Rafael,CA,97562,...,1165,210500.00,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep
1,129,Mini Wheels Co.,Murphy,Julie,6505555787,5557 North Pendale Street,,San Francisco,CA,94217,...,1165,64600.00,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep
2,161,Technics Stores Inc.,Hashimoto,Juri,6505556809,9408 Furth Circle,,Burlingame,CA,94217,...,1165,84600.00,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep
3,321,Corporate Gift Ideas Co.,Brown,Julie,6505551386,7734 Strong St.,,San Francisco,CA,94217,...,1165,105000.00,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep
4,450,The Sharp Gifts Warehouse,Frick,Sue,4085553659,3086 Ingle Ln.,,San Jose,CA,94217,...,1165,77600.00,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep
5,487,Signal Collectibles Ltd.,Taylor,Sue,4155554312,2793 Furth Circle,,Brisbane,CA,94217,...,1165,60300.00,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep
6,112,Signal Gift Stores,King,Jean,7025551838,8489 Strong St.,,Las Vegas,NV,83030,...,1166,71800.00,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep
7,205,Toys4GrownUps.com,Young,Julie,6265557265,78934 Hillside Dr.,,Pasadena,CA,90003,...,1166,90700.00,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep
8,219,Boards & Toys Co.,Young,Mary,3105552373,4097 Douglas Av.,,Glendale,CA,92561,...,1166,11000.00,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep
9,239,Collectable Mini Designs Co.,Thompson,Valarie,7605558146,361 Furth Circle,,San Diego,CA,91217,...,1166,105000.00,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep
10,347,"Men 'R' US Retailers, Ltd.",Chandler,Brian,2155554369,6047 Douglas Av.,,Los Angeles,CA,91003,...,1166,57700.00,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep
11,475,West Coast Collectables Co.,Thompson,Steve,3105553722,3675 Furth Circle,,Burbank,CA,94019,...,1166,55400.00,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep
12,173,Cambridge Collectables Co.,Tseng,Jerry,6175555555,4658 Baden Av.,,Cambridge,MA,51247,...,1188,43400.00,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep
13,204,Online Mini Collectables,Barajas,Miguel,6175557555,7635 Spinnaker Dr.,,Brickhaven,MA,58339,...,1188,68700.00,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep
14,320,Mini Creations Ltd.,Huang,Wing,5085559555,4575 Hillside Dr.,,New Bedford,MA,50553,...,1188,94500.00,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep
15,339,"Classic Gift Ideas, Inc",Cervantes,Francisca,2155554695,782 First Street,,Philadelphia,PA,71270,...,1188,81100.00,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep
16,379,Collectables For Less Inc.,Nelson,Allen,6175558555,7825 Douglas Av.,,Brickhaven,MA,58339,...,1188,70700.00,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep
17,495,Diecast Collectables,Franco,Valarie,6175552555,6251 Ingle Ln.,,Boston,MA,51003,...,1188,85100.00,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep
18,157,Diecast Classics Inc.,Leong,Kelvin,2155551555,7586 Pompton St.,,Allentown,PA,70267,...,1216,100600.00,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep
19,198,Auto-Moto Classics Inc.,Taylor,Leslie,6175558428,16780 Pompton St.,,Brickhaven,MA,58339,...,1216,23000.00,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep
20,286,Marta's Replicas Co.,Hernandez,Marta,6175558555,39323 Spinnaker Dr.,,Cambridge,MA,51247,...,1216,123700.00,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep
21,362,Gifts4AllAges.com,Yoshido,Juri,6175559555,8616 Spinnaker Dr.,,Boston,MA,51003,...,1216,41900.00,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep
22,363,Online Diecast Creations Co.,Young,Dorothy,6035558647,2304 Long Airport Avenue,,Nashua,NH,62005,...,1216,114200.00,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep
23,462,FunGiftIdeas.com,Benitez,Violeta,5085552555,1785 First Street,,New Bedford,MA,50553,...,1216,85800.00,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep
24,151,Muscle Machine Inc,Young,Jeff,2125557413,4092 Furth Circle,Suite 400,NYC,NY,10022,...,1286,138500.00,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep
25,168,American Souvenirs Inc,Franco,Keith,2035557845,149 Spinnaker Dr.,Suite 101,New Haven,CT,97823,...,1286,0.00,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep
26,181,Vitachrome Inc.,Frick,Michael,2125551500,2678 Kingston Rd.,Suite 101,NYC,NY,10022,...,1286,76400.00,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep
27,233,Québec Home Shopping Network,Fresnière,Jean,(514) 555-8054,43 rue St. Laurent,,Montréal,Québec,H1J 1C3,...,1286,48700.00,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep
28,424,Classic Legends Inc.,Hernandez,Maria,2125558493,5905 Pompton St.,Suite 750,NYC,NY,10022,...,1286,67500.00,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep
29,455,Super Scale Inc.,Murphy,Leslie,2035559545,567 North Pendale Street,,New Haven,CT,97823,...,1286,95400.00,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep
30,456,Microscale Inc.,Choi,Yu,2125551957,5290 North Pendale Street,Suite 200,NYC,NY,10022,...,1286,39800.00,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep
31,131,Land of Toys Inc.,Lee,Kwai,2125557818,897 Long Airport Avenue,,NYC,NY,10022,...,1323,114900.00,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
32,175,Gift Depot Inc.,King,Julie,2035552570,25593 South Bay Ln.,,Bridgewater,CT,97562,...,1323,84300.00,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
33,202,Canadian Gift Exchange Network,Tamuri,Yoshi,(604) 555-3392,1900 Oak St.,,Vancouver,BC,V3F 2K1,...,1323,90300.00,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
34,260,"Royal Canadian Collectables, Ltd.",Lincoln,Elizabeth,(604) 555-4555,23 Tsawassen Blvd.,,Tsawassen,BC,T2F 8M4,...,1323,89600.00,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
35,319,Mini Classics,Frick,Steve,9145554562,3758 North Pendale Street,,White Plains,NY,24067,...,1323,102700.00,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
36,328,Tekni Collectables Inc.,Brown,William,2015559350,7476 Moss Rd.,,Newark,NJ,94019,...,1323,43000.00,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
37,447,Gift Ideas Corp.,Lewis,Dan,2035554407,2440 Pompton St.,,Glendale,CT,97561,...,1323,49700.00,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
38,486,Motor Mint Distributors Inc.,Salazar,Rosa,2155559857,11328 Douglas Av.,,Philadelphia,PA,71270,...,1323,72600.00,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
39,146,"Saveley & Henriot, Co.",Saveley,Mary,78.32.5555,"2, rue du Commerce",,Lyon,,69004,...,1337,123900.00,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep
40,172,"La Corne D'abondance, Co.",Bertrand,Marie,(1) 42.34.2555,"265, boulevard Charonne",,Paris,,75012,...,1337,84300.00,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep
41,250,Lyon Souveniers,Da Silva,Daniel,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,,Paris,,75508,...,1337,68100.00,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep
42,350,Marseille Mini Autos,Lebihan,Laurence,91.24.4555,"12, rue des Bouchers",,Marseille,,13008,...,1337,65000.00,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep
43,353,Reims Collectables,Henriot,Paul,26.47.1555,59 rue de l'Abbaye,,Reims,,51100,...,1337,81100.00,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep
44,406,Auto Canal+ Petit,Perrier,Dominique,(1) 47.55.6555,"25, rue Lauriston",,Paris,,75016,...,1337,95000.00,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep
45,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",,Nantes,,44000,...,1370,21000.00,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep
46,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",,Nantes,,44000,...,1370,118200.00,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep
47,141,Euro+ Shopping Channel,Freyre,Diego,(91) 555 94 44,"C/ Moralzarzal, 86",,Madrid,,28034,...,1370,227600.00,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep
48,171,Daedalus Designs Imports,Rancé,Martine,20.16.1555,"184, chaussée de Tournai",,Lille,,59000,...,1370,82900.00,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep
49,209,Mini Caravy,Citeaux,Frédérique,88.60.1555,"24, place Kléber",,Strasbourg,,67000,...,1370,53800.00,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep

Notice that this also returned both columns: salesRepEmployeeNumber and employeeNumber.

## Summary

In this lesson you investigated joins including the on and using clause, aliasing table names, left joins and primary and foreign keys.